system:
    debug: 1
    timezone: 'UTC'
session:
    handler: native
    expire_time: 15
cache:
    enabled: 0
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
